/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// App : A Terminal App used for configuring an OAuth 2.0 client.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct App {
    /// Unique object identifier. The format and length of IDs may change over time.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the app.
    #[serde(rename = "name")]
    pub name: String,
    /// Redirect URI of the app.
    #[serde(rename = "redirectURI")]
    pub redirect_uri: String,
    /// OAuth 2.0 client secret of the app (obfuscated).
    #[serde(rename = "secret")]
    pub secret: String,
}

impl App {
    /// A Terminal App used for configuring an OAuth 2.0 client.
    pub fn new(id: String, name: String, redirect_uri: String, secret: String) -> App {
        App {
            id,
            name,
            redirect_uri,
            secret,
        }
    }
}

