/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CardExpiration : Expiration of the card.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CardExpiration {
    /// Expiration year of the card.
    #[serde(rename = "year")]
    pub year: i32,
    /// Expiration month of the card.
    #[serde(rename = "month")]
    pub month: i32,
}

impl CardExpiration {
    /// Expiration of the card.
    pub fn new(year: i32, month: i32) -> CardExpiration {
        CardExpiration {
            year,
            month,
        }
    }
}

