/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CartAmount : The subtotal and shipping amounts for the current user's cart.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CartAmount {
    /// Subtotal of the current user's cart, in cents (USD).
    #[serde(rename = "subtotal")]
    pub subtotal: i32,
    /// Shipping amount of the current user's cart, in cents (USD).
    #[serde(rename = "shipping", skip_serializing_if = "Option::is_none")]
    pub shipping: Option<i32>,
    /// Total amount after any discounts, in cents (USD).
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl CartAmount {
    /// The subtotal and shipping amounts for the current user's cart.
    pub fn new(subtotal: i32) -> CartAmount {
        CartAmount {
            subtotal,
            shipping: None,
            total: None,
        }
    }
}

