/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CartShipping : Shipping information for the current user's cart.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CartShipping {
    /// Shipping service name.
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    /// Shipping timeframe provided by the shipping carrier.
    #[serde(rename = "timeframe", skip_serializing_if = "Option::is_none")]
    pub timeframe: Option<String>,
}

impl CartShipping {
    /// Shipping information for the current user's cart.
    pub fn new() -> CartShipping {
        CartShipping {
            service: None,
            timeframe: None,
        }
    }
}

