/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CartItem : An item in the current Terminal shop user's cart.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CartItem {
    /// Unique object identifier. The format and length of IDs may change over time.
    #[serde(rename = "id")]
    pub id: String,
    /// ID of the product variant for this item in the current user's cart.
    #[serde(rename = "productVariantID")]
    pub product_variant_id: String,
    /// Quantity of the item in the current user's cart.
    #[serde(rename = "quantity")]
    pub quantity: i32,
    /// Subtotal of the item in the current user's cart, in cents (USD).
    #[serde(rename = "subtotal")]
    pub subtotal: i32,
}

impl CartItem {
    /// An item in the current Terminal shop user's cart.
    pub fn new(id: String, product_variant_id: String, quantity: i32, subtotal: i32) -> CartItem {
        CartItem {
            id,
            product_variant_id,
            quantity,
            subtotal,
        }
    }
}

