/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteAddressById200Response {
    #[serde(rename = "data")]
    pub data: Data,
}

impl DeleteAddressById200Response {
    pub fn new(data: Data) -> DeleteAddressById200Response {
        DeleteAddressById200Response {
            data,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Data {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Data {
    fn default() -> Data {
        Self::Ok
    }
}

