/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProduct200Response {
    /// A list of products.
    #[serde(rename = "data")]
    pub data: Vec<models::Product>,
}

impl GetProduct200Response {
    pub fn new(data: Vec<models::Product>) -> GetProduct200Response {
        GetProduct200Response {
            data,
        }
    }
}

