/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCard200Response {
    /// List of cards associated with the user.
    #[serde(rename = "data")]
    pub data: Vec<models::Card>,
}

impl GetCard200Response {
    pub fn new(data: Vec<models::Card>) -> GetCard200Response {
        GetCard200Response {
            data,
        }
    }
}

