/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostToken200ResponseData {
    /// Personal token ID.
    #[serde(rename = "id")]
    pub id: String,
    /// Personal access token. Include this in the Authorization header (`Bearer <token>`) when accessing the Terminal API.
    #[serde(rename = "token")]
    pub token: String,
}

impl PostToken200ResponseData {
    pub fn new(id: String, token: String) -> PostToken200ResponseData {
        PostToken200ResponseData {
            id,
            token,
        }
    }
}

