/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCardRequest {
    /// Stripe card token. Learn how to [create one here](https://docs.stripe.com/api/tokens/create_card).
    #[serde(rename = "token")]
    pub token: String,
}

impl PostCardRequest {
    pub fn new(token: String) -> PostCardRequest {
        PostCardRequest {
            token,
        }
    }
}

