/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductTags : Tags for the product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductTags {
    #[serde(rename = "app", skip_serializing_if = "Option::is_none")]
    pub app: Option<String>,
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<String>,
    #[serde(rename = "featured", skip_serializing_if = "Option::is_none")]
    pub featured: Option<bool>,
    #[serde(rename = "market_na", skip_serializing_if = "Option::is_none")]
    pub market_na: Option<bool>,
    #[serde(rename = "market_eu", skip_serializing_if = "Option::is_none")]
    pub market_eu: Option<bool>,
}

impl ProductTags {
    /// Tags for the product.
    pub fn new() -> ProductTags {
        ProductTags {
            app: None,
            color: None,
            featured: None,
            market_na: None,
            market_eu: None,
        }
    }
}

