/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductVariant : Variant of a product in the Terminal shop.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductVariant {
    /// Unique object identifier. The format and length of IDs may change over time.
    #[serde(rename = "id")]
    pub id: String,
    /// Name of the product variant.
    #[serde(rename = "name")]
    pub name: String,
    /// Price of the product variant in cents (USD).
    #[serde(rename = "price")]
    pub price: i32,
}

impl ProductVariant {
    /// Variant of a product in the Terminal shop.
    pub fn new(id: String, name: String, price: i32) -> ProductVariant {
        ProductVariant {
            id,
            name,
            price,
        }
    }
}

