/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Profile : A Terminal shop user's profile. (We have users, btw.)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Profile {
    #[serde(rename = "user")]
    pub user: Box<models::User>,
}

impl Profile {
    /// A Terminal shop user's profile. (We have users, btw.)
    pub fn new(user: models::User) -> Profile {
        Profile {
            user: Box::new(user),
        }
    }
}

