/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCartItemRequest {
    /// ID of the product variant to add to the cart.
    #[serde(rename = "productVariantID")]
    pub product_variant_id: String,
    /// Quantity of the item to add to the cart.
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl PutCartItemRequest {
    pub fn new(product_variant_id: String, quantity: i32) -> PutCartItemRequest {
        PutCartItemRequest {
            product_variant_id,
            quantity,
        }
    }
}

