/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCartAddressRequest {
    /// ID of the shipping address to set for the current user's cart.
    #[serde(rename = "addressID")]
    pub address_id: String,
}

impl PutCartAddressRequest {
    pub fn new(address_id: String) -> PutCartAddressRequest {
        PutCartAddressRequest {
            address_id,
        }
    }
}

