/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCartCardRequest {
    /// ID of the credit card to set for the current user's cart.
    #[serde(rename = "cardID")]
    pub card_id: String,
}

impl PutCartCardRequest {
    pub fn new(card_id: String) -> PutCartCardRequest {
        PutCartCardRequest {
            card_id,
        }
    }
}

