/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionSchedule : Schedule of the subscription.
/// Schedule of the subscription.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SubscriptionSchedule {
    Fixed(Box<models::Fixed>),
    Weekly(Box<models::Weekly>),
}

impl Default for SubscriptionSchedule {
    fn default() -> Self {
        Self::Fixed(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "fixed")]
    Fixed,
    #[serde(rename = "weekly")]
    Weekly,
}

impl Default for Type {
    fn default() -> Type {
        Self::Fixed
    }
}

