/*
 * Terminal API
 *
 * The Terminal API gives you access to the same API that powers the award winning Terminal SSH shop (`ssh terminal.shop`).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Token : A personal access token used to access the Terminal API. If you leak this, expect large sums of coffee to be ordered on your credit card.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Token {
    /// Unique object identifier. The format and length of IDs may change over time.
    #[serde(rename = "id")]
    pub id: String,
    /// The created time for the token.
    #[serde(rename = "created")]
    pub created: String,
    /// Personal access token (obfuscated).
    #[serde(rename = "token")]
    pub token: String,
}

impl Token {
    /// A personal access token used to access the Terminal API. If you leak this, expect large sums of coffee to be ordered on your credit card.
    pub fn new(id: String, created: String, token: String) -> Token {
        Token {
            id,
            created,
            token,
        }
    }
}

